version: '3.9'
services:
  gateway:
    image: maven:3.6.3-jdk-11
    container_name: gateway
    restart: unless-stopped
    ports:
      - 15000:5005
      - 18000:8080
    environment:
     GATEWAY_SERVICES: >-
       auth=http://auth:8080;
       backend=http://backend:8080;
     SERVICES_AUTH_HOST: http://auth:8080
     SERVICEACCOUNT_ROLE: ROLE_SERVICEACCOUNT
    working_dir: /app
    volumes:
     - maven_repo:/root/.m2
     - C:\Users\denis\Documents\Files\Projects\farmBot\gateway:/app
    command: bash -c "
     mvn clean compile -Dhttps.protocols=TLSv1.2 -Dmaven.test.skip=true &&
     mvn spring-boot:run -Dhttps.protocols=TLSv1.2 -Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005\""
    networks:
     - farmbot
      
  auth:
    image: maven:3.6.3-jdk-11
    container_name: auth
    restart: unless-stopped
    ports:
     - "18001:8080"
     - "15001:5005"
    environment:
     SERVICEACCOUNT_ROLE: ROLE_SERVICEACCOUNT
     DATABASE_URL: jdbc:postgresql:@postgres:5432/farm
     DATABASE_USERNAME: farmdb
     DATABASE_PASSWORD: postgres3
    working_dir: /app
    volumes:
     - maven_repo:/root/.m2
     - C:\Users\denis\Documents\Files\Projects\farmBot\auth:/app
    command: bash -c "
     mvn clean compile -Dhttps.protocols=TLSv1.2 -Dmaven.test.skip=true &&
     mvn spring-boot:run -Dhttps.protocols=TLSv1.2 -Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005\""
    networks:
     - farmbot

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: farmdb
      POSTGRES_PASSWORD: postgres3
      POSTGRES_DB: farm
    networks:
      - farmbot

  backend:
    image: maven:3.6.3-jdk-11
    container_name: backend
    ports:
      - 15004:5005
      - 18004:8080
    depends_on:
      - postgres
    environment:    
      SERVICEACCOUNT_ROLE: ROLE_SERVICEACCOUNT
      DATABASE_URL: jdbc:postgresql://postgres:5432/farm
      DATABASE_USERNAME: farmdb
      DATABASE_PASSWORD: postgres3
    working_dir: /app
    volumes:
      - maven_repo:/root/.m2
      - C:\Users\denis\Documents\Files\Projects\farmBot\backend:/app
    command: bash -c "
      mvn clean compile -Dhttps.protocols=TLSv1.2 -Dmaven.test.skip=true &&
      mvn spring-boot:run -Dhttps.protocols=TLSv1.2 -Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005\""
    networks:
      - farmbot

volumes:
  postgres_data:
  maven_repo:

networks:
  farmbot:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.18.0.0/24
