gateway:build-and-test:
  extends: .java-maven-build-and-test
  variables:
    APP_NAME: "gateway"
  only:
    changes:
      - "gateway/**/*"

gateway:sast:
  extends: .java-maven-sast
  variables:
    APP_NAME: "gateway"
    SONAR_TOKEN: "b97a7bd81981c24950247fff48a6d4f4f4cd28b7"
  only:
    changes:
      - "gateway/**/*"

gateway:publish:
  extends: .java-maven-publish
  variables:
    APP_NAME: "gateway"
  only:
    refs:
      - master@customs/frontiera
      - development@customs/frontiera
    changes:
      - "gateway/**/*"

gateway:increment-version-patch:
  extends: .java-maven-increment-version
  variables:
    INCREMENT_VERSION_OPTION: "p"
    APP_NAME: "gateway"
  only:
    refs:
      - development@customs/frontiera
    changes:
      - "gateway/**/*"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /hotfix/

gateway:increment-version-minor:
  extends: .java-maven-increment-version
  variables:
    INCREMENT_VERSION_OPTION: "m"
    APP_NAME: "gateway"
  only:
    refs:
      - master@customs/frontiera
    changes:
      - "gateway/**/*"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /hotfix/
      - $CI_COMMIT_MESSAGE =~ /ci release/

gateway:increment-version-major:
  extends: .java-maven-increment-version
  variables:
    INCREMENT_VERSION_OPTION: "M"
    APP_NAME: "gateway"
  only:
    refs:
      - master@customs/frontiera
    changes:
      - "gateway/**/*"
    variables:
      - $CI_COMMIT_MESSAGE =~ /ci release/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /hotfix/
