server:
  servlet:
    context-path: /
app:
  gateway:
    services: ${GATEWAY_SERVICES}
    ignore-origin-patterns: ${IGNORE_ORIGIN_PATTERNS:NONE}
  jwt:
    secret: ${JWT_SECRET:JWTSECRETSHOULDBE256BITSASPERJWTSPECIFICATIONRFC7518}
    expire: ${JWT_EXPIRE:86400}
  serviceaccount:
    role: ${SERVICEACCOUNT_ROLE:ROLE_SERVICEACCOUNT}
logging:
  level:
    root: INFO
services:
  auth:
    host: ${SERVICES_AUTH_HOST}
spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - PreserveHostHeader
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: WARN
    md.customs.frontiera: INFO
