server:
  servlet:
    context-path: /

app:
  model:
    package: md.utm.farmbot.backend.models
  jwt:
    secret: ${JWT_SECRET:JWTSECRETSHOULDBE256BITSASPERJWTSPECIFICATIONRFC7518}
    expire: ${JWT_EXPIRE:86400}
  serviceaccount:
    role: ${SERVICEACCOUNT_ROLE:ROLE_SERVICEACCOUNT}

logging:
  level:
    root: WARN
    md.utm.farmbot: INFO

services:
  backend:
    host: ${SERVICES_BACKEND:http://backend:8080}

management:
  endpoints:
    web:
      exposure:
        include: "info,health,metrics,mappings"

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  flyway:
    table: farm_flyway_schema_history
    locations: classpath:db/migration/{vendor}
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: true
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: false
  cloud:
    loadbalancer.ribbon.enabled: false
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true

javers:
  sqlSchemaManagementEnabled: false

schedule:
  enabled: ${SCHEDULER_ENABLED:false}

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    md.utm.farmbot: DEBUG
